# Position of static library is important.
# Position of include directory is important.
# Make sure that there are symbols in the static library:
# - ar -t libdvdread.a
# - nm libdvdread.a
# In obj/ directory
# - ar crs libdvdread2.a *.o
# - nm libdvdread2.a (now has the symbols)
# In the Makefile for "install-static", remove the $(INSTALLSTRIP) option and the static library symbols will be kept.
# INSTALLSTRIP is set in the config.mak generated by ./configure2 (INSTALLSTRIP=-s, which strips the symbol tables).
gcc -I/usr/local/include/dvdread -Wall -o test1.exe test1.c /usr/local/lib/libdvdread.a -L/usr/lib/i386-linux-gnu -ldl

